# Generated by Django 4.2.11 on 2024-03-24 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0010_qrcodehistory_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qrcodehistory',
            options={'ordering': ['-created_at']},
        ),
    ]
