# Generated by Django 4.2.11 on 2024-03-26 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store_app', '0013_getstarted'),
    ]

    operations = [
        migrations.AddField(
            model_name='getstarted',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='getstarted',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='getstarted',
            name='font_type',
            field=models.CharField(choices=[('Arial', 'Arial'), ('Times_New_Roman', 'Times New Roman'), ('Verdana', 'Verdana')], default='Arial', max_length=100),
        ),
        migrations.AlterField(
            model_name='getstarted',
            name='template_type',
            field=models.CharField(choices=[('Template1', 'Template 1'), ('Template2', 'Template 2')], default='Template1', max_length=100),
        ),
        migrations.AlterField(
            model_name='getstarted',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
