# Generated by Django 4.2.11 on 2024-03-27 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0014_getstarted_created_at_getstarted_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetStartedTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(blank=True, choices=[('Template1', 'Business'), ('Template2', 'Portfolio')], default='Template1', max_length=100, null=True)),
                ('font_type', models.CharField(blank=True, choices=[('Arial', 'Arial'), ('Times_New_Roman', 'Times New Roman'), ('Verdana', 'Verdana')], default='Arial', max_length=100, null=True)),
                ('color_theme', models.CharField(max_length=7)),
                ('html_content', models.TextField(blank=True)),
                ('css_content', models.TextField(blank=True)),
                ('js_content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='getstarted',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='getstarted',
            name='template_type',
            field=models.CharField(choices=[('Template1', 'Business'), ('Template2', 'Portfolio')], default='Template1', max_length=100),
        ),
    ]
