# Generated by Django 4.2.11 on 2024-03-27 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store_app', '0015_getstartedtemplate_alter_getstarted_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='getstartedtemplate',
            name='color_theme',
        ),
        migrations.RemoveField(
            model_name='getstartedtemplate',
            name='font_type',
        ),
        migrations.CreateModel(
            name='GetStartedUserTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_type', models.CharField(choices=[('Arial', 'Arial'), ('Times_New_Roman', 'Times New Roman'), ('Verdana', 'Verdana')], default='Arial', max_length=100)),
                ('color_theme', models.CharField(max_length=7)),
                ('business_name', models.CharField(max_length=100)),
                ('business_logo', models.ImageField(blank=True, null=True, upload_to='business_logos/')),
                ('additional_field', models.TextField(blank=True)),
                ('html_content', models.TextField(blank=True)),
                ('css_content', models.TextField(blank=True)),
                ('js_content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
