# Generated by Django 4.2.11 on 2024-03-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0016_remove_getstartedtemplate_color_theme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='getstartedtemplate',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='getstartedtemplate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='started_templates/'),
        ),
        migrations.AddField(
            model_name='getstartedtemplate',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='getstartedusertemplate',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='getstartedusertemplate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='started_templates/'),
        ),
        migrations.AddField(
            model_name='getstartedusertemplate',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
