# Generated by Django 4.2.11 on 2024-03-27 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0017_getstartedtemplate_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GetStartedTemplate',
        ),
        migrations.AddField(
            model_name='templates',
            name='template_type',
            field=models.CharField(blank=True, choices=[('Template1', 'Business'), ('Template2', 'Portfolio')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usertemplate',
            name='additional_field',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usertemplate',
            name='business_logo',
            field=models.ImageField(blank=True, null=True, upload_to='business_logos/'),
        ),
        migrations.AddField(
            model_name='usertemplate',
            name='business_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usertemplate',
            name='color_theme',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='usertemplate',
            name='font_type',
            field=models.CharField(blank=True, choices=[('Arial', 'Arial'), ('Times_New_Roman', 'Times New Roman'), ('Verdana', 'Verdana')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usertemplate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='templates/'),
        ),
        migrations.AlterField(
            model_name='usertemplate',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_templates', to='store_app.templates'),
        ),
        migrations.DeleteModel(
            name='GetStartedUserTemplate',
        ),
    ]
