# Generated by Django 4.2.11 on 2024-03-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0018_delete_getstartedtemplate_templates_template_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='templates',
            name='customizable',
            field=models.BooleanField(default=False),
        ),
    ]
