# Generated by Django 4.2.11 on 2024-03-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0019_templates_customizable'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertemplate',
            name='font_family',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usertemplate',
            name='font_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
