# Generated by Django 4.2.11 on 2024-03-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0020_usertemplate_font_family_usertemplate_font_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertemplate',
            name='font_link',
        ),
        migrations.AlterField(
            model_name='getstarted',
            name='font_type',
            field=models.CharField(choices=[('Roboto', 'Roboto'), ('Open Sans', 'Open Sans'), ('Lato', 'Lato'), ('Montserrat', 'Montserrat'), ('Reddit Mono', 'Reddit Mono'), ('Edu NSW', 'Edu NSW')], default='Arial', max_length=100),
        ),
        migrations.AlterField(
            model_name='usertemplate',
            name='font_family',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usertemplate',
            name='font_type',
            field=models.CharField(blank=True, choices=[('Roboto', 'Roboto'), ('Open Sans', 'Open Sans'), ('Lato', 'Lato'), ('Montserrat', 'Montserrat'), ('Reddit Mono', 'Reddit Mono'), ('Edu NSW', 'Edu NSW')], max_length=100, null=True),
        ),
    ]
