# Generated by Django 4.2.11 on 2024-03-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0021_remove_usertemplate_font_link_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedImage',
        ),
        migrations.AlterField(
            model_name='getstarted',
            name='font_type',
            field=models.CharField(choices=[('Roboto', 'Roboto'), ('Open Sans', 'Open Sans'), ('Lato', 'Lato'), ('Montserrat', 'Montserrat'), ('Reddit Mono', 'Reddit Mono'), ('Edu NSW', 'Edu NSW')], default='Roboto', max_length=100),
        ),
        migrations.DeleteModel(
            name='WebsiteTemplate',
        ),
    ]
