# Generated by Django 4.2.11 on 2024-03-27 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store_app', '0022_delete_uploadedimage_alter_getstarted_font_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.usertemplate')),
            ],
        ),
        migrations.CreateModel(
            name='TAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.usertemplate')),
            ],
        ),
    ]
