# Generated by Django 4.2.11 on 2024-03-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0023_tuser_tadmin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='getstarted',
            old_name='color_theme',
            new_name='color_theme_pr',
        ),
        migrations.RenameField(
            model_name='usertemplate',
            old_name='color_theme',
            new_name='color_theme_pr',
        ),
        migrations.AddField(
            model_name='getstarted',
            name='color_theme_sc',
            field=models.CharField(default=1, max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usertemplate',
            name='color_theme_sc',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
