# Generated by Django 4.2.11 on 2024-03-27 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0024_rename_color_theme_getstarted_color_theme_pr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.usertemplate')),
            ],
        ),
        migrations.DeleteModel(
            name='TUser',
        ),
    ]
