# Generated by Django 4.2.11 on 2024-03-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0026_alter_contact_options_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='templates',
            name='barber',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usertemplate',
            name='barber',
            field=models.BooleanField(default=False),
        ),
    ]
