# Generated by Django 4.2.11 on 2024-03-30 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0027_templates_barber_usertemplate_barber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TAdmin',
        ),
    ]
