# Generated by Django 4.2.11 on 2024-04-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0028_delete_tadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getstarted',
            name='template_type',
            field=models.CharField(choices=[('Template1', 'Business'), ('Template2', 'Portfolio'), ('Template3', 'CleanIt')], default='Template1', max_length=100),
        ),
        migrations.AlterField(
            model_name='templates',
            name='template_type',
            field=models.CharField(blank=True, choices=[('Template1', 'Business'), ('Template2', 'Portfolio'), ('Template3', 'CleanIt')], max_length=100, null=True),
        ),
    ]
