# Generated by Django 4.2.11 on 2024-04-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0029_alter_getstarted_template_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getstarted',
            name='template_type',
            field=models.CharField(choices=[('Template1', 'Business'), ('Template2', 'Portfolio'), ('Template3', 'CleanIt'), ('Template4', 'Barber Shop'), ('Template5', 'Tech Inovations')], default='Template1', max_length=100),
        ),
        migrations.AlterField(
            model_name='templates',
            name='template_type',
            field=models.CharField(blank=True, choices=[('Template1', 'Business'), ('Template2', 'Portfolio'), ('Template3', 'CleanIt'), ('Template4', 'Barber Shop'), ('Template5', 'Tech Inovations')], max_length=100, null=True),
        ),
    ]
