# Generated by Django 4.2.11 on 2024-04-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0033_availabletime_booking_remove_seeappointment_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabletime',
            name='time',
            field=models.JSONField(),
        ),
    ]
