# Generated by Django 4.2.11 on 2024-04-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0034_alter_availabletime_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabletime',
            name='endTime',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='availabletime',
            name='startTime',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='availabletime',
            name='time',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
