# Generated by Django 4.2.11 on 2024-04-13 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store_app", "0036_alter_booking_options_booking_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="replied",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contact",
            name="replied_message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
