# Generated by Django 4.2.11 on 2024-04-13 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0037_contact_replied'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='replied_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
