# Generated by Django 4.2.11 on 2024-04-14 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0039_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='user_template',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store_app.usertemplate'),
        ),
    ]
