# Generated by Django 4.2.11 on 2024-04-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0042_alter_domain_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='custom_domain',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
